server:
  port: 8888

spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:////Users/areeba/Desktop/udemy-workspaces/config-server-files