server:
  port: 8888

spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/majdhaidar/config-server-files-spring-three.git
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "533e99f2-f770-42fa-af2d-5fa46d15ad84"